/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CourseRouteImport } from './routes/course/route'
import { Route as IndexImport } from './routes/index'
import { Route as CourseIndexImport } from './routes/course/index'
import { Route as CourseSuggestionImport } from './routes/course/suggestion'
import { Route as CourseMyCourseImport } from './routes/course/my-course'
import { Route as CourseCommunityImport } from './routes/course/community'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthSigninImport } from './routes/auth/signin'
import { Route as CourseCourseidIndexImport } from './routes/course/$courseid/index'

// Create/Update Routes

const CourseRouteRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CourseIndexRoute = CourseIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseRouteRoute,
} as any)

const CourseSuggestionRoute = CourseSuggestionImport.update({
  id: '/suggestion',
  path: '/suggestion',
  getParentRoute: () => CourseRouteRoute,
} as any)

const CourseMyCourseRoute = CourseMyCourseImport.update({
  id: '/my-course',
  path: '/my-course',
  getParentRoute: () => CourseRouteRoute,
} as any)

const CourseCommunityRoute = CourseCommunityImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => CourseRouteRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any)

const CourseCourseidIndexRoute = CourseCourseidIndexImport.update({
  id: '/$courseid/',
  path: '/$courseid/',
  getParentRoute: () => CourseRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/course/community': {
      id: '/course/community'
      path: '/community'
      fullPath: '/course/community'
      preLoaderRoute: typeof CourseCommunityImport
      parentRoute: typeof CourseRouteImport
    }
    '/course/my-course': {
      id: '/course/my-course'
      path: '/my-course'
      fullPath: '/course/my-course'
      preLoaderRoute: typeof CourseMyCourseImport
      parentRoute: typeof CourseRouteImport
    }
    '/course/suggestion': {
      id: '/course/suggestion'
      path: '/suggestion'
      fullPath: '/course/suggestion'
      preLoaderRoute: typeof CourseSuggestionImport
      parentRoute: typeof CourseRouteImport
    }
    '/course/': {
      id: '/course/'
      path: '/'
      fullPath: '/course/'
      preLoaderRoute: typeof CourseIndexImport
      parentRoute: typeof CourseRouteImport
    }
    '/course/$courseid/': {
      id: '/course/$courseid/'
      path: '/$courseid'
      fullPath: '/course/$courseid'
      preLoaderRoute: typeof CourseCourseidIndexImport
      parentRoute: typeof CourseRouteImport
    }
  }
}

// Create and export the route tree

interface CourseRouteRouteChildren {
  CourseCommunityRoute: typeof CourseCommunityRoute
  CourseMyCourseRoute: typeof CourseMyCourseRoute
  CourseSuggestionRoute: typeof CourseSuggestionRoute
  CourseIndexRoute: typeof CourseIndexRoute
  CourseCourseidIndexRoute: typeof CourseCourseidIndexRoute
}

const CourseRouteRouteChildren: CourseRouteRouteChildren = {
  CourseCommunityRoute: CourseCommunityRoute,
  CourseMyCourseRoute: CourseMyCourseRoute,
  CourseSuggestionRoute: CourseSuggestionRoute,
  CourseIndexRoute: CourseIndexRoute,
  CourseCourseidIndexRoute: CourseCourseidIndexRoute,
}

const CourseRouteRouteWithChildren = CourseRouteRoute._addFileChildren(
  CourseRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course': typeof CourseRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/course/community': typeof CourseCommunityRoute
  '/course/my-course': typeof CourseMyCourseRoute
  '/course/suggestion': typeof CourseSuggestionRoute
  '/course/': typeof CourseIndexRoute
  '/course/$courseid': typeof CourseCourseidIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/course/community': typeof CourseCommunityRoute
  '/course/my-course': typeof CourseMyCourseRoute
  '/course/suggestion': typeof CourseSuggestionRoute
  '/course': typeof CourseIndexRoute
  '/course/$courseid': typeof CourseCourseidIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/course': typeof CourseRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/course/community': typeof CourseCommunityRoute
  '/course/my-course': typeof CourseMyCourseRoute
  '/course/suggestion': typeof CourseSuggestionRoute
  '/course/': typeof CourseIndexRoute
  '/course/$courseid/': typeof CourseCourseidIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/course'
    | '/auth/signin'
    | '/auth/signup'
    | '/course/community'
    | '/course/my-course'
    | '/course/suggestion'
    | '/course/'
    | '/course/$courseid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signin'
    | '/auth/signup'
    | '/course/community'
    | '/course/my-course'
    | '/course/suggestion'
    | '/course'
    | '/course/$courseid'
  id:
    | '__root__'
    | '/'
    | '/course'
    | '/auth/signin'
    | '/auth/signup'
    | '/course/community'
    | '/course/my-course'
    | '/course/suggestion'
    | '/course/'
    | '/course/$courseid/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseRouteRoute: typeof CourseRouteRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseRouteRoute: CourseRouteRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/course",
        "/auth/signin",
        "/auth/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/course": {
      "filePath": "course/route.tsx",
      "children": [
        "/course/community",
        "/course/my-course",
        "/course/suggestion",
        "/course/",
        "/course/$courseid/"
      ]
    },
    "/auth/signin": {
      "filePath": "auth/signin.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/course/community": {
      "filePath": "course/community.tsx",
      "parent": "/course"
    },
    "/course/my-course": {
      "filePath": "course/my-course.tsx",
      "parent": "/course"
    },
    "/course/suggestion": {
      "filePath": "course/suggestion.tsx",
      "parent": "/course"
    },
    "/course/": {
      "filePath": "course/index.tsx",
      "parent": "/course"
    },
    "/course/$courseid/": {
      "filePath": "course/$courseid/index.tsx",
      "parent": "/course"
    }
  }
}
ROUTE_MANIFEST_END */
