/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AmuRouteImport } from './routes/amu/route'
import { Route as IndexImport } from './routes/index'
import { Route as AmuIndexImport } from './routes/amu/index'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthSigninImport } from './routes/auth/signin'
import { Route as AmuMyCourseImport } from './routes/amu/my-course'

// Create/Update Routes

const AmuRouteRoute = AmuRouteImport.update({
  id: '/amu',
  path: '/amu',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AmuIndexRoute = AmuIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AmuRouteRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any)

const AmuMyCourseRoute = AmuMyCourseImport.update({
  id: '/my-course',
  path: '/my-course',
  getParentRoute: () => AmuRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/amu': {
      id: '/amu'
      path: '/amu'
      fullPath: '/amu'
      preLoaderRoute: typeof AmuRouteImport
      parentRoute: typeof rootRoute
    }
    '/amu/my-course': {
      id: '/amu/my-course'
      path: '/my-course'
      fullPath: '/amu/my-course'
      preLoaderRoute: typeof AmuMyCourseImport
      parentRoute: typeof AmuRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/amu/': {
      id: '/amu/'
      path: '/'
      fullPath: '/amu/'
      preLoaderRoute: typeof AmuIndexImport
      parentRoute: typeof AmuRouteImport
    }
  }
}

// Create and export the route tree

interface AmuRouteRouteChildren {
  AmuMyCourseRoute: typeof AmuMyCourseRoute
  AmuIndexRoute: typeof AmuIndexRoute
}

const AmuRouteRouteChildren: AmuRouteRouteChildren = {
  AmuMyCourseRoute: AmuMyCourseRoute,
  AmuIndexRoute: AmuIndexRoute,
}

const AmuRouteRouteWithChildren = AmuRouteRoute._addFileChildren(
  AmuRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amu': typeof AmuRouteRouteWithChildren
  '/amu/my-course': typeof AmuMyCourseRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/amu/': typeof AmuIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amu/my-course': typeof AmuMyCourseRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/amu': typeof AmuIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/amu': typeof AmuRouteRouteWithChildren
  '/amu/my-course': typeof AmuMyCourseRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/amu/': typeof AmuIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amu'
    | '/amu/my-course'
    | '/auth/signin'
    | '/auth/signup'
    | '/amu/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/amu/my-course' | '/auth/signin' | '/auth/signup' | '/amu'
  id:
    | '__root__'
    | '/'
    | '/amu'
    | '/amu/my-course'
    | '/auth/signin'
    | '/auth/signup'
    | '/amu/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmuRouteRoute: typeof AmuRouteRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmuRouteRoute: AmuRouteRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/amu",
        "/auth/signin",
        "/auth/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/amu": {
      "filePath": "amu/route.tsx",
      "children": [
        "/amu/my-course",
        "/amu/"
      ]
    },
    "/amu/my-course": {
      "filePath": "amu/my-course.tsx",
      "parent": "/amu"
    },
    "/auth/signin": {
      "filePath": "auth/signin.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/amu/": {
      "filePath": "amu/index.tsx",
      "parent": "/amu"
    }
  }
}
ROUTE_MANIFEST_END */
